name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Specify the correct PHP version here
        tools: composer

    - name: Install Dependencies
      run: composer install --no-dev --prefer-dist --no-progress --no-interaction
    
    - name: Run Tests
      run: php artisan test

    - name: Deploy to Forge
      env:
        FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
        FORGE_SERVER_ID: ${{ secrets.FORGE_SERVER_ID }}
        FORGE_SITE_ID: ${{ secrets.FORGE_SITE_ID }}
      run: |
        curl -X POST "https://forge.laravel.com/api/v1/servers/${{ secrets.FORGE_SERVER_ID }}/sites/${{ secrets.FORGE_SITE_ID }}/deploy" \
        -H "Authorization: Bearer ${{ secrets.FORGE_API_TOKEN }}"
