name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Set to your PHP version
        extensions: mbstring, intl, pdo, bcmath, json, xml

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader

    - name: Run Laravel tests
      run: php artisan test

    - name: Run PHP CS Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install NPM dependencies
      run: npm install

    - name: Build assets
      run: npm run prod

    - name: Deploy to Forge
      env:
        FORGE_SERVER_ID: ${{ secrets.FORGE_SERVER_ID }}
        FORGE_SITE_ID: ${{ secrets.FORGE_SITE_ID }}
        FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
      run: |
        curl -X POST "https://forge.laravel.com/api/v1/servers/${FORGE_SERVER_ID}/sites/${FORGE_SITE_ID}/deployment/deploy" \
        -H "Authorization: Bearer ${FORGE_API_TOKEN}" \
        -H "Content-Type: application/json"
