name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # or your specific PHP version

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: php artisan test

      - name: Deploy to Forge
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
        run: |
          curl -s -X POST "https://forge.laravel.com/api/v1/servers/{server_id}/sites/{site_id}/deploy" \
          -H "Authorization: Bearer ${FORGE_API_TOKEN}" \
          -H "Accept: application/json"
